/**
 * VEIL Relay Server & Protocol Types (Protocol Version 1).
 *
 * Defines the contract for untrusted blind mailboxes, opaque envelopes,
 * capability authorization, and WebSocket frames.
 */

export const RELAY_PROTOCOL_VERSION = 'v1';

export type RelayErrorCode =
  | 'BAD_REQUEST'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'PAYLOAD_TOO_LARGE'
  | 'RATE_LIMITED'
  | 'EXPIRED'
  | 'CONFLICT'
  | 'STORAGE_UNAVAILABLE'
  | 'INTERNAL_ERROR';

export interface RelayEnvelope {
  protocolVersion: 'v1';
  envelopeId: string;
  mailboxId: string;
  payload: string; // Base64 opaque ciphertext generated by client
  createdAt: number;
  expiresAt: number;
  sizeBytes: number;
}

export interface MailboxRecord {
  mailboxId: string;
  capabilityHash: string; // SHA-256(capabilityToken) hex digest
  createdAt: number;
  expiresAt: number;
  lastActiveAt: number;
}

export interface CreateMailboxRequest {
  ttlSeconds?: number;
}

export interface CreateMailboxResponse {
  protocolVersion: 'v1';
  mailboxId: string;
  capabilityToken: string; // Secret capability token (returned once to client)
  expiresAt: number;
}

export interface SendEnvelopeRequest {
  mailboxId: string;
  payload: string; // Base64 ciphertext <= 64 KiB
  ttlSeconds?: number;
}

export interface SendEnvelopeResponse {
  protocolVersion: 'v1';
  envelopeId: string;
  mailboxId: string;
  expiresAt: number;
  sizeBytes: number;
}

export interface FetchEnvelopesRequest {
  mailboxId: string;
  capabilityToken: string;
  limit?: number;
}

export interface FetchEnvelopesResponse {
  protocolVersion: 'v1';
  mailboxId: string;
  envelopes: RelayEnvelope[];
  hasMore: boolean;
}

export interface AckEnvelopesRequest {
  mailboxId: string;
  capabilityToken: string;
  envelopeIds: string[];
}

export interface AckEnvelopesResponse {
  protocolVersion: 'v1';
  mailboxId: string;
  acknowledgedCount: number;
}

export interface RelayErrorResponse {
  error: {
    code: RelayErrorCode;
    message: string;
    status: number;
  };
}

// WebSocket Protocol Types
export type ClientWsMessage =
  | { type: 'auth'; mailboxId: string; capabilityToken: string }
  | { type: 'ping' }
  | { type: 'ack'; envelopeIds: string[] };

export type ServerWsMessage =
  | { type: 'authenticated'; mailboxId: string }
  | { type: 'pong' }
  | { type: 'envelope'; envelope: RelayEnvelope }
  | { type: 'ack_confirm'; acknowledgedCount: number }
  | { type: 'error'; code: RelayErrorCode; message: string };

// Directory Protocol Types
export type { SignedProfileDocument } from '../identity/profile.ts';
import type { SignedProfileDocument } from '../identity/profile.ts';

export interface RegisterProfileRequest {
  profile: SignedProfileDocument;
}

export interface RegisterProfileResponse {
  protocolVersion: 'v1';
  success: boolean;
  username: string;
  identityId: string;
}

export interface DirectorySearchResult {
  identityId: string;
  username: string;
  displayName: string;
  avatar?: string;
  profileSignature: string;
  bio?: string;
}

export interface DirectorySearchResponse {
  protocolVersion: 'v1';
  results: DirectorySearchResult[];
  query: string;
}

export interface DirectoryProfileResponse {
  protocolVersion: 'v1';
  profile: SignedProfileDocument;
}
